; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; PSRAM activé (ESP32-WROVER ou module avec PSRAM soudée)
build_flags  = -DBOARD_HAS_PSRAM -DCONFIG_SPIRAM_SUPPORT=1

; Bibliothèques Arduino utilisées
lib_deps     =
    ESP32 BLE Arduino          ; BLEDevice / BLEServer / BLECharacteristic

monitor_speed = 115200

; Tests unitaires (PlatformIO native)
[env:native]
platform = native